### ISSUE TITLE
http 502

### ISSUE THREAD

**Issue by vitalis0itu** [Sanoma/sanoma-election-machine-algorithms#2]
Saan http 502 vastauksia kutsusta 
POST https://vaalikone-api.datadesk.hs.fi/match?electionId=eduskunta2023

En löytänyt sopivaa aspan yhteytietoa. Tämä vaikuttaa pääsevän lähimmäs ongelman yhdintä. Tässä 17.49 kokeilin viimeksi asiaa.

**Comment by quarian** [comment]
Jäi tämä huomaamatta, mutta oletettavasti oli ajallista pientä ongelmaa.
